name: Build
on: [push]
jobs:
  python-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: flake8 .

  unit-tests:
    needs: python-formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  
          pip install -r requirements.txt  
          python -m pytest --version
      - name: Run Tests
        working-directory: src
        run: python -m pytest

  deploy-to-impaas:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: ImPaaS-Deploy
          uses: /impaas/impaas-deploy@v3
          with:
            app-name: tg1424-sse-app
            deployment-token: ${{ secrets.TSURU_TOKEN_SSE }}
            method: PLATFORM
